[project]
name = "mlscratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.9",
    "mlxtend>=0.23.4",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "pillow>=12.3.0",
    "rich>=15.0.0",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "tqdm>=4.70.0",
    "ucimlrepo>=0.0.7",
]

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mlscratch"]
